### ISSUE TITLE
Add tests for no-rain combinations

### ISSUE THREAD

**Issue by ladc** [mpvginde/pysteps#18] opened 2023-08-09 15:31 UTC
Add tests for the different combinations of no rain in NWP, radar, and both. 
@RubenImhoff could you pull the version in my [hackaton](https://github.com/ladc/pysteps/tree/hackaton) branch and check if your case still works there? Thanks a lot!
I currently get errors for my tests (more specifically the decomposed precip still contains nans)

**Comment by RubenImhoff** [comment] 2023-08-09 15:35
Will try to do so tomorrow! Weird that it still gives errors..

**Comment by RubenImhoff** [comment] 2023-08-10 15:25
Hi Lesley, I have not yet been able to reproduce your errors. Considering the errors in the precip (that is precip_radar, I suppose?) still containing nans, could it be that it does not give zero_precip_radar back and thus continues with the precip_radar throughout the entire forecasting loop? If that is not the reason, we will have to dive into what really is going wrong, based on the case you are using.

**Comment by RubenImhoff** [comment] 2023-08-11 15:27
I think I found the problem. Due to the recent change to a renormalization in the extrapolation step, we could get nans in the precip_radar variable again during the extrapolation steps. This is fixed now in commit https://github.com/mpvginde/pysteps/commit/a399ffaa0079f23dd566fafd2455555a49d79e49. @ladc, can you check the code and check if everything works well now?

**Comment by ladc** [comment] 2023-08-16 12:27
Yes, it seems to work now. The returned array just had the wrong dimensions (normally we don't add the nowcast for t=0)
I've added some tests and they all pass now. These changes are implemented in #19

**Closed as completed** 2023-08-16 12:27 UTC
